### ISSUE TITLE
Compilação Dockerfile

### ISSUE THREAD

**Issue by krymancer** [reu/rinha-backend-rust#1]
Eu tenho esse Dokerfile

````
FROM rust:latest AS build
WORKDIR /usr/src/app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY .sqlx ./.sqlx
RUN cargo build --release
RUN cargo install --path .
FROM debian:bullseye-slim
COPY --from=build /usr/local/cargo/bin/api_rust_rinha_back /usr/local/bin/api_rust_rinha_back
CMD ["api_rust_rinha_back"]
````

Mas sempre que tentto rodar o docker build . me retorna isso:
53.14 error: `DATABASE_URL` must be set, or `cargo sqlx prepare` must have been run and .sqlx must exist, to use query macros
53.14    --> src/main.rs:128:18

Vi tentei meio que copiar teu Dockerfile mas n funciou.
Quando eu coloco uma .env no container com um endereço do postgress retorna:
error: error communicating with database: Cannot assign requested address (os error 99)
Provavelmente pq o container não consegue achar

Desculpa perguntar aqui, é que eu já esgotei td que pude achar sobre

**Comment by krymancer** [comment]
Consegui, eu tique que fazer 
> cargo sqlx prepare

**Comment by reu** [comment]
Nossa @Krymancer foi mal, eu só to vendo isso agora hahaha

Mas show que vc já descobriu, realmente o sqlx tem essa inconveniênca se vc quiser usar os macros...

**Comment by krymancer** [comment]
> Nossa @Krymancer foi mal, eu só to vendo isso agora hahaha
> 
> Mas show que vc já descobriu, realmente o sqlx tem essa inconveniênca se vc quiser usar os macros...

Tranquilo, eu to aprendendo rust agora, então tem várias coisas que eu ainda to penando haha.
Aprendi várias coisas com teu repo.
Inclusive se n for pedir de mais se puder dar um feedback na minha API https://github.com/Krymancer/rinha-de-backend-2023-q3-rust, foi o que consegui fazer sozinho, dai depois fui tentando usar teu repo e do @viniciusfonseca pra tentar deixar mais performática (inclusive toda a parte do postgres que eu n manjo eu basicamente so copiei de vcs)

**Comment by reu** [comment]
Claro dou uma olhada sim! Mas é, Rust tem uma curva de aprendizado tensa, no começo tudo é difícil hehehe

Mas pow, vc conseguiu terminar a API toda, já tá excelente!
